apiVersion: apps/v1
kind: Deployment
metadata:
  name: requirement-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requirement-api
  template:
    metadata:
      labels:
        app: requirement-api
    spec:
      containers:
      - name: requirement-api
        image: sandycis476/requirements:latest
        ports:
        - containerPort: 8111
--- 
apiVersion: v1
kind: Service
metadata:
  name: requirement-api
spec:
  selector:
    app: requirement-api
  ports:
  - protocol: TCP
    port: 8111         # Port exposed to the Ingress
    targetPort: 8111 # Port in the application pod
  type: ClusterIP

